package model;

import java.io.Serializable;

public interface CollegeIf{

	int PERSONBAG_MAXSIZE = 10000;
	int TEXTBOOKBAG_MAXSIZE = 40000;
	int MASTER_COURSEBAG_MAXSIZE = 10000;
	int CLASSROOMBAG_MAXSIZE = 10000;
	int MINI_STUDENT_COURSEBAG_MAXSIZE = 10000;
	int MINI_FACUTY_COURSEBAG_MAXSIZE = 10000;
}
